### ISSUE TITLE
Does IESX allow for more than one attribute?

### ISSUE THREAD

**Issue by EvanBianco** [agile-geoscience/gio#9]
Upon exporting a horizon from OpendTect to IESX format I see that, "only the first attribute will be used".

Is this restriction of the IESX format, or just in the way OpendTect creates them?

Suggestion: we should creates IESX files from Petrel, etc., to see if the format will handle more than one attribute and engineer appropriately. 

![image](https://user-images.githubusercontent.com/1699959/148796258-457972b0-300f-48ca-87f5-04a2980519bb.png)

**Comment by kwinkunks** [comment]
Not according to... you! https://earthscience.stackexchange.com/a/4902/70

**Comment by EvanBianco** [comment]
Ha! Well isn't that cute.
